#ifndef NSYNC_PLATFORM_GCC_NO_TLS_COMPILER_H_
#define NSYNC_PLATFORM_GCC_NO_TLS_COMPILER_H_

#define INLINE __inline
#define UNUSED __attribute__((unused))
#define THREAD_LOCAL
#define HAVE_THREAD_LOCAL 0

#endif /*NSYNC_PLATFORM_GCC_NO_TLS_COMPILER_H_*/
