#ifndef NSYNC_PLATFORM_POSIX_COMPILER_H_
#define NSYNC_PLATFORM_POSIX_COMPILER_H_

#define INLINE
#define UNUSED
#define THREAD_LOCAL
#define HAVE_THREAD_LOCAL 0

#endif /*NSYNC_PLATFORM_POSIX_COMPILER_H_*/
