#ifndef NSYNC_PLATFORM_POSIX_NSYNC_TIME_INIT_H_
#define NSYNC_PLATFORM_POSIX_NSYNC_TIME_INIT_H_

#define NSYNC_TIME_STATIC_INIT(t,ns) { (t), (ns) }

#endif /*NSYNC_PLATFORM_POSIX_NSYNC_TIME_INIT_H_*/
