#ifndef NSYNC_PLATFORM_MSVC_COMPILER_H_
#define NSYNC_PLATFORM_MSVC_COMPILER_H_

#define INLINE __inline
#define UNUSED
#define THREAD_LOCAL __declspec(thread)
#define HAVE_THREAD_LOCAL 1

#endif /*NSYNC_PLATFORM_MSVC_COMPILER_H_*/
