DETECT=../../tools/detect.sh

all:; ${DETECT} "${CC}" ${MAKE} -f Makefile.helper all
tests:; ${DETECT} "${CC}" ${MAKE} -f Makefile.helper tests
test:; ${DETECT} "${CC}" ${MAKE} -f Makefile.helper test
depend:; ${DETECT} "${CC}" ${MAKE} -f Makefile.helper depend
clean:; ${DETECT} "${CC}" ${MAKE} -f Makefile.helper clean
